version: "3"
services:
    nifi:
        image: nifi_ext:latest
        ports:
            - "8083:8080"
            - "8001:8001"
            - "8002:8002"
        volumes:
            - ./volumes/state:/opt/nifi/nifi-current/state
            - ./app:/app
            - ./src:/src
